import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Osama Nori Portfolio Website</title>
        <meta name="description" content="website"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className={styles.title}>Welcome To My Portfolio Website</h1>

      {/*my stupid way*/}

      {/* <div className={styles.gallery}>
        <div className={styles.unsetImg}>
          <Image
            src="/green_trees.jpg"
            layout="fill"
            className={styles.image}
          ></Image>
        </div>

        <div className={styles.unsetImg}>
          <Image
            src="/green_trees.jpg"
            layout="fill"
            className={styles.image}
          ></Image>

          <Image
            src="/green_trees.jpg"
            layout="fill"
            className={styles.image}
          ></Image>
        </div>
  </div>*/}
      <div className={styles.imageGallery}>
        <Link href="/education" scroll={false}>
          <a className={styles.img_1}>
            <text>Education</text>
          </a>
        </Link>
        <Link href="/web_development" scroll={false}>
          <a className={styles.img_2}>
            <text>Web Development</text>
          </a>
        </Link>
        <Link href="/programming_languages" scroll={false}>
          <a className={styles.img_3}>
            <text>Programming Languages</text>
          </a>
        </Link>
        <Link href="/game_development" scroll={false}>
          <a className={styles.img_4}>
            <text>Game Development</text>
          </a>
        </Link>
        <Link href="/mobile_development" scroll={false}>
          <a className={styles.img_5}>
            <text>Mobile Development</text>
          </a>
        </Link>
        <Link href="/other_skills" scroll={false}>
          <a className={styles.img_6}>
            <text>Other Skills</text>
          </a>
        </Link>

        {/*<a href="/green_trees.jpg" className={styles.img_7}>
          <text>Hello</text>
        </a>
        <a href="/green_trees.jpg" className={styles.img_8}>
          <text>Hello</text>
</a>*/}
      </div>
    </div>

    /*<div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>*/
  );
}
